server:
  port: 9096

spring:
  config:
    name: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/online_edu?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
#    url: jdbc:mysql://localhost:3306/online_edu?useSSL=false&useUnicode=true&characterEncoding=UTF8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  servlet:
    multipart:
      max-file-size: 1GB
      max-request-size: 1GB
  redis:
    host: localhost
    port: 6379
#    password: 123456
    timeout: 3000

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    default-enum-type-handler: com.baomidou.mybatisplus.extension.handlers.MybatisEnumTypeHandler
  mapper-locations:
    - classpath:xyz.refrain/onlineedu/mapper/xml/*.xml

# aliyun
aliyun:
  access-key-id: LTAI5tBcZqnTSeyhcN2ivZiL
  access-key-secret: gpUqRxMbRMgKFotwyBjQFag8gbrOp6
  oss:
    bucket-name: ooss0001
    endpoint: oss-cn-beijing.aliyuncs.com
  vod:
    region-id: cn-shanghai




